# Generated by Django 5.0.7 on 2024-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('hour', models.CharField(max_length=50)),
            ],
        ),
    ]
