# Generated by Django 5.0.7 on 2024-07-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
